#!/usr/bin/env python3
"""Builds the ari-lecco-cad-pi.img.xz release asset.

Downloads the current official Raspberry Pi OS Lite (arm64) image, patches
its boot partition's cloud-init user-data so the Pi provisions itself on
first boot (default pi/arilecco login forced to change on first login,
mDNS hostname ari-cad, and a systemd unit that runs pi-setup/bootstrap.sh
once network is up), then recompresses it for distribution.

Requires: pyfatfs, PyYAML (see pi-setup/build-requirements.txt).

Usage:
    python3 build-pi-image.py --output dist/ari-lecco-cad-pi.img.xz
"""
import argparse
import struct
import subprocess
import sys
import textwrap
import urllib.request
from pathlib import Path

BASE_IMAGE_URL = "https://downloads.raspberrypi.com/raspios_lite_arm64_latest"
FAT32_PARTITION_TYPES = {0x0B, 0x0C}
SECTOR_SIZE = 512

REPO_ROOT = Path(__file__).resolve().parent.parent
BOOTSTRAP_SH = REPO_ROOT / "pi-setup" / "bootstrap.sh"

SYSTEMD_UNIT = """\
[Unit]
Description=ARI Lecco CAD first-boot provisioning
After=network-online.target
Wants=network-online.target
ConditionPathExists=!/opt/ari-lecco-cad/.env

[Service]
Type=oneshot
ExecStart=/bin/sh /opt/ari-lecco-cad/bootstrap.sh
StandardOutput=journal+console
StandardError=journal+console
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target
"""


def find_fat32_boot_offset(img_path: Path) -> int:
    """Parses the MBR to find the FAT32 boot partition's byte offset."""
    with open(img_path, "rb") as f:
        mbr = f.read(SECTOR_SIZE)
    if mbr[510:512] != b"\x55\xaa":
        raise ValueError("Not a valid MBR disk image")
    for i in range(4):
        entry = mbr[0x1BE + i * 16 : 0x1BE + (i + 1) * 16]
        part_type = entry[4]
        lba_start = struct.unpack("<I", entry[8:12])[0]
        if part_type in FAT32_PARTITION_TYPES and lba_start:
            return lba_start * SECTOR_SIZE
    raise ValueError("No FAT32 boot partition found in MBR")


def build_user_data() -> str:
    bootstrap_sh = BOOTSTRAP_SH.read_text()
    indented_bootstrap = textwrap.indent(bootstrap_sh, " " * 6)
    indented_unit = textwrap.indent(SYSTEMD_UNIT, " " * 6)
    return f"""\
#cloud-config
# ARI Lecco CAD appliance image -- auto-generated by pi-setup/build-pi-image.py
# from pi-setup/bootstrap.sh. Do not hand-edit on a flashed card.

hostname: ari-cad
manage_etc_hosts: true

users:
  - name: pi
    gecos: ARI Lecco CAD
    groups: [sudo, adm, dialout, audio, video, plugdev, games, users, input, netdev]
    shell: /bin/bash
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL

# Default SSH/console login is pi / arilecco. cloud-init forces a password
# change on first login (console or SSH) via the expire flag below.
chpasswd:
  expire: true
  users:
    - name: pi
      password: arilecco
      type: text

ssh_pwauth: true

package_update: true
packages:
  - avahi-daemon

write_files:
  - path: /opt/ari-lecco-cad/bootstrap.sh
    permissions: '0755'
    owner: root:root
    content: |
{indented_bootstrap}

  - path: /etc/systemd/system/ari-lecco-cad-bootstrap.service
    permissions: '0644'
    owner: root:root
    content: |
{indented_unit}

runcmd:
  - systemctl daemon-reload
  - systemctl enable --now ari-lecco-cad-bootstrap.service
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--workdir", type=Path, default=Path("pi-image-build"))
    args = parser.parse_args()

    args.workdir.mkdir(parents=True, exist_ok=True)
    base_xz = args.workdir / "base.img.xz"
    base_img = args.workdir / "base.img"

    print(f"==> Downloading {BASE_IMAGE_URL}")
    urllib.request.urlretrieve(BASE_IMAGE_URL, base_xz)

    print("==> Decompressing base image")
    subprocess.run(["xz", "-d", "-f", "-k", "-T0", str(base_xz)], check=True)

    offset = find_fat32_boot_offset(base_img)
    print(f"==> FAT32 boot partition at byte offset {offset}")

    user_data = build_user_data()
    print(f"==> Patching cloud-init user-data ({len(user_data)} bytes)")

    # Imported here so --help works even before pyfatfs/pyyaml are installed.
    import yaml
    from pyfatfs.PyFatFS import PyFatFS

    parsed = yaml.safe_load(user_data)
    assert parsed["hostname"] == "ari-cad", "sanity check on generated YAML failed"

    fs = PyFatFS(str(base_img), offset=offset, read_only=False)
    fs.remove("/user-data")
    with fs.openbin("/user-data", "w") as out:
        out.write(user_data.encode())
    written_back = fs.readbytes("/user-data")
    fs.close()
    assert written_back == user_data.encode(), "readback of patched user-data did not match"

    args.output.parent.mkdir(parents=True, exist_ok=True)
    print(f"==> Compressing to {args.output}")
    subprocess.run(
        ["xz", "-T0", "-6", "-c", str(base_img)],
        check=True,
        stdout=open(args.output, "wb"),
    )

    print(f"==> Done: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
